### ISSUE TITLE
Task details page, don't show proper details, page is broken

### ISSUE THREAD

**Issue by prakashchoudhary07** [Real-Dev-Squad/website-status#1004]
The page looks broken, either show proper details or show some message that its not accessible

Will have to discuss this with the team for acceptance criteria

<img width="1644" alt="image" src="https://github.com/Real-Dev-Squad/website-status/assets/34452139/1fcd1e67-6925-48c3-9809-a1fb5bbc764a">

**Comment by bhtibrewal** [comment]
This issue comes under the dashboard site,  and being worked upon by some developer there, so closing this issue ticket.
