### ISSUE TITLE
Adding some transition effect on button click or hover

### ISSUE THREAD

**Issue by vikhyat187** [Real-Dev-Squad/website-status#1006]
Here on the progress updates page, it will be better if we  have some transition effect on the hover and click of `Submit button`
<img width="344" alt="image" src="https://github.com/Real-Dev-Squad/website-status/assets/52795644/0975c682-fdd9-47d3-bf73-388149b02584">

**Comment by bhtibrewal** [comment]
also from a user perspective even after i submitted the progress the inputs stayed as it is giving the feel it can still be edited, user should be redirected after submit or the inputs should go into read-only state

**Comment by ajoykumardas12** [comment]
This issue was fixed #1046
