### ISSUE TITLE
Navbar --- mobile view need correction 

### ISSUE THREAD

**Issue by skv93-coder** [Real-Dev-Squad/website-status#1019]
[
![Screenshot_20231122-104504](https://github.com/Real-Dev-Squad/website-status/assets/68867418/bf765890-370b-481a-81a6-f6b77c9416a8)
](url)

**Comment by anmoljhamb** [comment]
Hey! I'd like to work on this issue! And it would be my first time contributing to open source, so if you have any tips, I'd appericiate it!

**Comment by skv93-coder** [comment]
Hey I think you are not part of realdevsquad.com. first apply there I think in jan there will be opening you can try then.
