### ISSUE TITLE
Update lib version from 2017 to 2021

### ISSUE THREAD

**Issue by ardourApeX** [Real-Dev-Squad/website-status#1025]
### Issue Description
Currently, we have `"lib": ["dom", "es2017"]` in tsconfig. Due to this, it is not allowed to use the .replaceAll method on strings, as it was introduced in 2021.

### Expected Behavior

Changing the `lib version to 2021` will enable us to use replaceAll with strings as well.

### Current Behavior

Due to the lib version specified as 2017, it does not allow the use of replaceAll with strings.

### Screenshots

![image](https://github.com/Real-Dev-Squad/website-status/assets/56365512/4c0e0f91-66de-4189-91ce-b3024cf230c9)

### Severity/Priority
 - [ ] Critical
 - [ ] High
 - [x] Medium
 - [ ] Low

### Checklist

- [x] I have read and followed the project's code of conduct.
- [x] I have searched for similar issues before creating this one.
- [x] I have provided all the necessary information to understand and reproduce the issue.
- [x] I am willing to contribute to the resolution of this issue.

---

Thank you for contributing to our project! We appreciate your help in improving it.

**Comment by ajoykumardas12** [comment]
close via #1026
