### ISSUE TITLE
UI/UX: "Progress update" component UI/UX improvement

### ISSUE THREAD

**Issue by satyam73** [Real-Dev-Squad/website-status#1053]
# "Progress update" component UI/UX improvement
## Overview

In status site we want to improve the progress update component UI and make it look more user-friendly.
Currently in progress updates section we show timelines of updates. Now we want that value under "Completed" section to show as title.

## **User Story**

- As a user, I want the component to look appealing UI wise.
- As a user, I should see "Completed" section string as title in progress updates component.
- As a user, I should see dates like `1 day ago`, `2 days ago`, ` a month ago`, `a year ago` .
- As a user, on hovering over the date I should see tooltip with full dates shown on the tooltip. **[1]**
- As a user, I should filter with filters `ascending` or `descending`.
- As a user, when I click on the component, modal should open with all the information of a progress update.
- As a user, I should see latest/recent progress update on top.
- As a user, I should see latest card with all the details of a progress update.

## Requirements
- We have to follow TDD(Test Driven Development).

## Images for reference

![image](https://github.com/Real-Dev-Squad/website-status/assets/85296770/e87bc25b-b749-4f6c-8cf2-2318c3235e1e)
> Current progress updates section with dates as title

![image](https://github.com/Real-Dev-Squad/website-status/assets/85296770/f84cf36a-7544-4f76-b74c-f31d43db8c39)
> [1] image of date tooltip shown when hovering over the dates like `1 day ago`, `2 days ago`, ` a month ago`, `a year ago`

## Acceptance Criteria

- [ ] As a user, I should see the component's title to be, value under "completed" part.
- [ ] As a user, I should see dates like `1 day ago`, `2 days ago`, ` a month ago`, `a year ago` on the component.
- [ ] As a user, on hovering over the date I should see tooltip with full dates shown on the tooltip. **[1]**
- [ ] As a user, I should see latest/recent progress update on top.
- [ ] As a user, I should filter with filters `ascending` or `descending`.
- [ ] As a user, when I click on the component, modal should open with all the information of a progress update.
- [ ] As a user, I should see latest card with all the details of a progress update.

**Comment by Ajeyakrishna-k** [comment]
> As a user, I should see dates like 1 day ago, 2 days ago,  a month ago, a year ago .

- If it is 16days ago what will be shown to user? 2weeks and 2 days ago or just 2weeks ago? 
- Will we show days and hours? eg: 2d 23hr ago?

**Comment by satyam73** [comment]
> * As a user, I should see latest/recent progress update on top.

- For 36 hours to 25 days	we will show 2 days ago ... 25 days ago
- No, it will be seconds, minutes, hours, days, months, years ago only
