### ISSUE TITLE
Request Task button is disabled 

### ISSUE THREAD

**Issue by vvaibhavdesai** [Real-Dev-Squad/website-status#1077]
### Issue Description
- Request task button is disabled for me 

### Expected Behavior
The Request task button should not be disabled for me

### Screenshots
![image](https://github.com/Real-Dev-Squad/website-status/assets/64726586/1ab51f4c-11e0-4490-b50d-8840123d976d)

### Reproducibility

 - [ ] This issue is reproducible
 - [ ] This issue is not reproducible

### Steps to Reproduce
1. get an old task which was already assigned to you
2, search for it in the status site

### Severity/Priority
 - [ ] Critical
 - [X] High
 - [ ] Medium
 - [ ] Low

### Checklist

- [ ] I have read and followed the project's code of conduct.
- [ ] I have searched for similar issues before creating this one.
- [ ] I have provided all the necessary information to understand and reproduce the issue.
- [ ] I am willing to contribute to the resolution of this issue.

**Comment by ajoykumardas12** [comment]
The button was disabled because a Task already existed for this particular issue.
