### ISSUE TITLE
Footer on 'Status' page not accessible - UX issue

### ISSUE THREAD

**Issue by Akansh97** [Real-Dev-Squad/website-status#1146]
### Issue Description
When scrolling down on the Status page, the footer moves further down as additional tasks load, making it less accessible until all tasks have been loaded. 
[Status Page URL](https://status.realdevsquad.com/tasks?q=status%3Aavailable)

### Expected Behavior
The footer should remain fixed in its position.

### Current Behavior
The footer is not fixed and continuously moves downward to the bottom of the page, becoming inaccessible.

### Screenshots
![Status Page Screenshot](https://github.com/Real-Dev-Squad/website-status/assets/47331547/57a45188-077a-43f3-9d9e-aef2676ca0f0)

### Reproducibility

- [x] This issue is reproducible
- [ ] This issue is not reproducible

### Steps to Reproduce
1. Scroll down on the Status page.
2. Try to click on the repository link.

### Severity/Priority
- [ ] Critical
- [ ] High
- [ ] Medium
- [x] Low

### Additional Information
This issue can likely be addressed with a simple HTML/CSS fix.

### Checklist

- [x] I have read and followed the project's code of conduct.
- [x] I have searched for similar issues before creating this one.
- [x] I have provided all the necessary information to understand and reproduce the issue.
- [x] I am willing to contribute to the resolution of this issue.

**Comment by ajoykumardas12** [comment]
Don't think the footer should be fixed on the screen, the main content will have shorter space then.
The content of this footer is focused towards people outside RDS, and status site is for internal use.

Please confirm once if it needs to be fixed from Ankush/Tejas/Prakash.
