### ISSUE TITLE
Planned must not have leading or trailing white space on progrees update form 

### ISSUE THREAD

**Issue by Achintya-Chatterjee** [Real-Dev-Squad/website-status#1158]
### Issue Description

When I'm filling up my progress form on a particular task getting a trailing white space problem, but after I copy the entire text to WhatsApp or on notes, and paste it back on the form, the entire bug is gone
### Screenshots

[Screencast from 24-02-24 11:32:19 PM IST.webm](https://github.com/Real-Dev-Squad/website-status/assets/55826451/c4017de2-fcbe-4021-b78d-cbe53efe729a)
[Screencast from 29-02-24 05:39:24 AM IST.webm](https://github.com/Real-Dev-Squad/website-status/assets/55826451/1fb29a78-d1e4-4c7c-b146-4441173f3655)

### Reproducibility

 - [x] This issue is reproducible
 - [ ] This issue is not reproducible

### Steps to Reproduce
1. 
2. 

### Severity/Priority
 - [ ] Critical
 - [ ] High
 - [ ] Medium
 - [ ] Low

### Checklist

- [ ] I have read and followed the project's code of conduct.
- [ ] I have searched for similar issues before creating this one.
- [ ] I have provided all the necessary information to understand and reproduce the issue.
- [ ] I am willing to contribute to the resolution of this issue.

**Comment by Atifsid** [comment]
I would like to work on this issue
