### ISSUE TITLE
Remove shadows from the task cards

### ISSUE THREAD

**Issue by ankushdharkar** [Real-Dev-Squad/website-status#116]
Add a background color for each card to be `#F9F9F9`, so it ends up looking like this:

![image](https://user-images.githubusercontent.com/1935403/114426046-84b38f00-9b6e-11eb-985c-0be663849175.png)

**Comment by rio14** [comment]
I want to take it up!!

**Comment by whyDontI** [comment]
Closing this as the requirements are handled in https://github.com/Real-Dev-Squad/website-status/issues/114
