### ISSUE TITLE
Cookie is not being sent with API requests

### ISSUE THREAD

**Issue by saxenaaman628** [Real-Dev-Squad/website-status#121]
## Problem
- [Mine](https://status.realdevsquad.com/mine) page on status site is not working
## Possible solution
- Try to include `withCredentials=true` in the `helperfunction/fetch`
- Reference https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/withCredentials

**Comment by maheshjadhav8378** [comment]
please assign this to me
