### ISSUE TITLE
Arrange cards in grid format

### ISSUE THREAD

**Issue by whyDontI** [Real-Dev-Squad/website-status#128]
Arrange the cards displayed in openPrs and stalePrs pages in grid format

https://staging-status.realdevsquad.com/openPRs
https://staging-status.realdevsquad.com/stale-pr

**Comment by whyDontI** [comment]
Not needed now.
Single column format is ok for now.

**Comment by kamara-moses** [comment]
Ok


Sent from Yahoo Mail for iPhone


On Friday, June 25, 2021, 1:16 PM, Nikhil Bhandarkar ***@***.***> wrote:




Not needed now.
Single column format is ok for now.
