### ISSUE TITLE
Update task card font sizing

### ISSUE THREAD

**Issue by ankushdharkar** [Real-Dev-Squad/website-status#143]
Update the font sizing of the current task card to match the [figma design](https://www.figma.com/file/KAV9FsUXlzhdFbHBADiZSk/Task-Row?node-id=0%3A1)
![image](https://user-images.githubusercontent.com/1935403/120961469-bf6f1900-c712-11eb-8e39-c2de92771e02.png)

**Comment by akshay1502** [comment]
I would like to this task. Assign it to me.

**Comment by ankushdharkar** [comment]
@akshay1502 Assigned! Please send the PR when ready :)
