### ISSUE TITLE
Add a dummy picture for the members without profile picture

### ISSUE THREAD

**Issue by whyDontI** [Real-Dev-Squad/website-status#151]
Use this picture
https://github.com/Real-Dev-Squad/website-status/blob/develop/public/dummyProfile.png

<img width="1920" alt="Screenshot 2021-06-14 at 9 09 30 PM" src="https://user-images.githubusercontent.com/26569942/121932857-fbcdf500-cd62-11eb-9c4b-da95c6ba7aa0.png">

**Comment by NoLayerCode** [comment]
Hi, I would like to take this issue

**Comment by abhinav1590** [comment]
I am interested in working on this issue
