### ISSUE TITLE
Add a dummy picture in Card component

### ISSUE THREAD

**Issue by whyDontI** [Real-Dev-Squad/website-status#152]
## Cause
https://github.com/Real-Dev-Squad/website-backend/issues/387

## Requirement
Show [dummy profile image](https://github.com/Real-Dev-Squad/website-status/blob/develop/public/dummyProfile.png) when there is no picture or a broken image URL in Card component

## Live issue
https://staging-status.realdevsquad.com/challenges

**Comment by akshay1502** [comment]
Assign this to me

**Comment by akshay1502** [comment]
#157
