### ISSUE TITLE
Cursor should not be pointer if underlying component is not clickable

### ISSUE THREAD

**Issue by whyDontI** [Real-Dev-Squad/website-status#159]
The cursor should be default if the card does not have a `link` in title `prop`

> You might want to wait for below GIF to load 👇🏽 
<img src="https://user-images.githubusercontent.com/26569942/122797650-52947b00-d2dd-11eb-8b01-f0bbab93af5f.gif" width="300px" />

**Comment by nilisha-jais** [comment]
I want to work on it
