### ISSUE TITLE
Staging Api Server Error

### ISSUE THREAD

**Issue by Runner-dev** [Real-Dev-Squad/website-status#160]
I was trying to fix the cursor pointer issue and when trying to install the app and run it locally I kept getting an error, when I opened the console I saw a server error was being returned from the staging api https://staging-api.realdevsquad.com/tasks but the real api ran fine https://api.realdevsquad.com/tasks is this an error on my part and if so how should I run the app locally to try to fix the issue?

**Comment by whyDontI** [comment]
Hello @Runner-dev,
Thanks for notifying, someone is already working on the staging API issue.

This is not recommended but till we get the issue fixed you might want to use production API endpoint.

You need to change `base URL` in .env.development file,
And make sure you don't commit the change.

Feel free to ask any doubts here
Thanks

**Comment by swarajpure** [comment]
You can make the change in `.env.local`
Env variables in this file will override all other env variables and it won't get committed also since it's in gitignore 😉
