### ISSUE TITLE
Few enhancements on availability panel

### ISSUE THREAD

**Issue by Pavangbhat** [Real-Dev-Squad/website-status#165]
- [x] avoid forceful reloading of the page on task assignment 
- [x] display avatar if the image is broken
- [x] use variables in CSS
- [x] hide tasks and idle users when patch request is processing 

Design link: https://www.figma.com/file/krYzdCT45ikzDDZ2tsUQaS/Tasks-Assignment?node-id=1%3A2

**Comment by whyDontI** [comment]
Designs for error handling -
https://www.figma.com/file/n6KtE3DJcC3H2EWpioxRhF/Alert-Message?node-id=2%3A79
