### ISSUE TITLE
Arrange the cards in idle members section alphabetically

### ISSUE THREAD

**Issue by harshith-venkatesh** [Real-Dev-Squad/website-status#167]
Currently, we see the members are sorted alphabetically but there is a error here due to which we see two names at top.
The effort involves reading about ascii codes, reading sort method in JS and adding relevant changes

https://media.discordapp.net/attachments/741616265050849282/859129265554587718/unknown.png?width=471&height=473

**Comment by harshith-venkatesh** [comment]
![https://media.discordapp.net/attachments/741616265050849282/859129265554587718/unknown.png?width=471&height=473]

**Comment by Devashish0210** [comment]
I will take this up

**Comment by rohan09-raj** [comment]
I want to take this up. Please assign.

**Comment by harshith-venkatesh** [comment]
The issue concerned here is, we are sorting the data according to user name.
In Javascript sorting on words works based on ascii values. 
Consider the situation here
Aa
aA
In the above case Aa < aA so we would be seeing Aa appearing before aA or even Za appearing before aa
We need a solution which would ensure, this edge cases is handled
