### ISSUE TITLE
Run lint check on Pull request

### ISSUE THREAD

**Issue by whyDontI** [Real-Dev-Squad/website-status#168]
Setup GitHub workflow to run lint checks on Pull Requests / code Push,

Reference - 
https://docs.github.com/en/enterprise-server@2.22/actions/learn-github-actions/introduction-to-github-actions#the-components-of-github-actions

**Comment by priyanshk20** [comment]
Can I try this?

**Comment by iRahulP** [comment]
@whyDontI , Should I add it to existing workflow or setup a new workflow?
