### ISSUE TITLE
Exclude "UNASSIGNED" tasks from overdue highlight

### ISSUE THREAD

**Issue by Devashish0210** [Real-Dev-Squad/website-status#173]
Currently, all tasks (except "COMPLETED") which have overshot their deadlines are being given a red border and highlighted. We want the "UNASSIGNED" tasks to be excluded from the overdue tasks list (similar to "COMPLETED" tasks).

A picture of current "UNASSIGNED" tasks - 
![image](https://user-images.githubusercontent.com/69790529/127963587-7d6ce3e2-b80b-489d-8d48-770a428887df.png)

Expected picture of "UNASSIGNED" tasks after this issue is fixed - 
![image](https://user-images.githubusercontent.com/69790529/127963669-fa012b63-a5bd-4a87-84e4-57fa3c0fb8e1.png)

**Comment by abhinav1590** [comment]
I m interested in taking this issue

**Comment by abhinav1590** [comment]
#186

**Comment by abhinav1590** [comment]
This issue fixes at #186
