### ISSUE TITLE
PRs doesn't load on bigger screens

### ISSUE THREAD

**Issue by whyDontI** [Real-Dev-Squad/website-status#174]
On [OpenPR](https://staging-status.realdevsquad.com/openPRs) and [StalePR](https://staging-status.realdevsquad.com/stale-pr) pages we have infinite scroll implemented.
As the scroller hits the bottom page loads the next set of PRs.
This doesn't seem to work on bigger screens.

<img width="1950" alt="Screenshot 2021-08-03 at 11 07 48 AM" src="https://user-images.githubusercontent.com/26569942/127964407-6d3cccae-a80e-488a-ab39-47e11826456b.png">

**Comment by rohandhar1234** [comment]
Please assign it to me
