### ISSUE TITLE
Place the title where it should actually belong

### ISSUE THREAD

**Issue by sumitd94** [Real-Dev-Squad/website-status#19]
Currently if you take a look at `challenges` screen & `Mine` screen, we have title text being displayed on the screen

![image](https://user-images.githubusercontent.com/29303618/102470744-5f0ff080-407a-11eb-89a1-93ba78240faa.png)

![image](https://user-images.githubusercontent.com/29303618/102470790-6931ef00-407a-11eb-9157-374bba655da5.png)

Please remove them from here and place the title where it should actually belong

![image](https://user-images.githubusercontent.com/29303618/102471043-b9a94c80-407a-11eb-80d3-c6a9724fb0c9.png)

**Comment by Khanjan04** [comment]
I will do it by tonight.
