### ISSUE TITLE
Tasks page edit mode

### ISSUE THREAD

**Issue by whyDontI** [Real-Dev-Squad/website-status#210]
Requirements - 
- Holding down the `Alt/option` key for 300ms should put the page in edit mode
- Show a pencil icon in the top-right corner of the screen once in edit mode

**Comment by VenomFate-619** [comment]
Can I do this ?

**Comment by whyDontI** [comment]
@VenomFate-619 Thanks for your interest but there is a [similar issue](https://github.com/Real-Dev-Squad/website-status/issues/222) and someone is already working on it.
Please feel free to check out other issues 🙃
