### ISSUE TITLE
Task details page

### ISSUE THREAD

**Issue by whyDontI** [Real-Dev-Squad/website-status#211]
# Requirements
- [x] #249
- [ ] Clicking on the task should open the details page
- [ ] Show comments history
- [ ] Show action history (Add/Remove assignee, update due date, etc.)

Check [this](https://github.com/Real-Dev-Squad/website-todo-items/issues/34) RFC discussion for a logging service
we'll use this service for history

**Comment by whyDontI** [comment]
@saxenaaman628 Let's not wait for comments and audit history to be added to the task.
Let's build the page showing the details we already have.

**Comment by saxenaaman628** [comment]
@whyDontI Ok I will push changes by 10th.
