### ISSUE TITLE
Fix the navbar

### ISSUE THREAD

**Issue by rohan09-raj** [Real-Dev-Squad/website-status#213]
### Design of New Navbar:
https://www.figma.com/file/bpFHG9hXM13GSLmTkoNsrF/Navbar?node-id=0%3A1

## Few Details 
- font : Roboto
- weight: 700
- active color : #49A82E
- hover color : #49A82E
- font size : 16 px (try making it in rem)
- active underline height : 3px (color : #49A82E)
- RDS Logo Size - 50x50

### Pay Attention
=> Underline should be under the text as shown in the image and not inside the container in which the text persists.
=> Underline should be only under the active tab, it should not be visible on hover
=> Clicking on RDS logo we should be redirected to https://www.realdevsquad.com/
=> The full navbar should be changed to the toggle menu when the screen width is less than 970px.

**Comment by jjagannn** [comment]
Hey Rohan, Can I try this in parallel with Shashank?
