### ISSUE TITLE
Enable edit mode for `super user` 

### ISSUE THREAD

**Issue by harshith-venkatesh** [Real-Dev-Squad/website-status#222]
Enable edit mode for `super user || admin user` to re-route to `/?edit=true` on click of button

## Requirements
- [x] Show a pencil icon on the ~~top-right of the screen~~ bottom-left of the cards in tasks
- [x] Keep it hidden by default
- [x] Make it visible on the long-press (300ms) of the Option/ALT
- [x] #246

Reach out to @harshith-venkatesh  for more information
![image](https://user-images.githubusercontent.com/42349041/185215411-2257c34a-44ef-480f-a6f6-e04a3b70d679.png)

**Comment by Kshashank99** [comment]
can i take this task

**Comment by Kshashank99** [comment]
ETA-25 jan

**Comment by harshith-venkatesh** [comment]
Question: 
```1. What does it mean by super user || admin user, are all members already super user or only AOs or only someone who is working on that particular issue
2. When long pressed of ALT/Option, what all things the user can edit in task section? 
3. How should i start. Do i need to get the design first before working on it? ```

**Comment by harshith-venkatesh** [comment]
Discussion:
```
1. Super user || admin , so if you refer to member's API contract, we have roles being assigned upon which certain actions could be performed.
Here: admin is assigned to @ankush  for sure , or it can be different roles in future. Focus should be to ensure the feature is role based.
2. Good question, if you observe status site with params of edit=true .
Admin || Super User as of now has already have an feature where he/she can perform multiple action.
The problem statement here is admin|super user has to manually enter dev=true to ensure the task is performed.
Can we look into the way where on long press click of alt/option we provide an option more like an icon(pencil maybe) which is visible only to admin|super user and it remains visible and enter the edit mode on click of the button to ensure that the process is not tedious.
```

**Comment by ankushdharkar** [comment]
@Maheima Could you follow up with the progress for this please?

**Comment by Maheima** [comment]
sure

**Comment by harshith-venkatesh** [comment]
- Currently, super-user need to type it manually to enter edit mode

- We need to automate that when super user clicks for a specific time
- I understand that but how are we figuring out which is the super user and which is not. I want to see the UI of SU how can I do that?
- We need a local backend setup pointed to fire store.
- One thing that can be done is to check the roles of the logged-in user
Probably now we can change the role to user/member and test the scenario and once we are confident then make the feature only available for superuser

**Comment by Maheima** [comment]
Changes requested earlier:
The icon was requested to be on the top right of the screen:
![image](https://user-images.githubusercontent.com/42349041/185217758-c9a8dbaa-bd4b-4e50-884b-da0756450ef0.png)
- For this, I made changes in layout/index.tsx and pages/index.tsx .
- Was working on solving prop drilling-related issues and making layout as a HOC

After a discussion with @ankushdharkar  on 17/08/22, the required icon is to be put on the bottom left of the card:
![image](https://user-images.githubusercontent.com/42349041/185218022-e9541a87-dec4-497d-a7f5-a512bac214aa.png)

**Comment by harshith-venkatesh** [comment]
Thanks for the update on the issue @Maheima
