### ISSUE TITLE
Progressbar should show green if the task is 100%

### ISSUE THREAD

**Issue by vinayak-trivedi** [Real-Dev-Squad/website-status#287]
currently the progress indicator shows yellow in some cases even when the task is done 100%, it should show green

Image for reference⬇️

![image](https://user-images.githubusercontent.com/90315175/185777543-e8655f26-ebff-4f34-a02d-d6b8f5917a1b.png)

**Comment by YashJain24-chief** [comment]
I can try resolving this issue
