### ISSUE TITLE
Card component rendering 33 times

### ISSUE THREAD

**Issue by Maheima** [Real-Dev-Squad/website-status#295]
[src/components/tasks/card/index.tsx](https://github.com/Real-Dev-Squad/website-status/blob/develop/src/components/tasks/card/index.tsx) is rendering many times. Is there a reason for it?
![image](https://user-images.githubusercontent.com/42349041/187108691-d5a0f6e8-d6b8-42d1-99f4-adf3ca26237a.png)

**Comment by harshith-venkatesh** [comment]
Could you also list the count of all tasks received from API response please

**Comment by harshith-venkatesh** [comment]
If we have 33 tasks listed from API response, then we might have 33 cards created which gets rendered
This is one possibility which could be ruled out if we have data backed

**Comment by Maheima** [comment]
resolved
