### ISSUE TITLE
multiple API calls are being made in Status page of RDS 

### ISSUE THREAD

**Issue by Pujarini** [Real-Dev-Squad/website-status#305]
<img width="1440" alt="Screen Shot 2022-09-06 at 10 26 03 AM" src="https://user-images.githubusercontent.com/34391629/188582427-76e7a016-bf75-44b6-84c2-48ceb1935447.png">

**Comment by Pujarini** [comment]
This error occurs as soon as user clicks on status tab.

**Comment by Maheima** [comment]
Fixed by https://github.com/Real-Dev-Squad/website-status/pull/306
