### ISSUE TITLE
Set up Github Actions

### ISSUE THREAD

**Issue by swarajpure** [Real-Dev-Squad/website-status#33]
Github actions need to be set up

Why is it needed?
- If `npm run build` fails for a particular PR/commit, we will get notified that the build is failing for this one. So that we can avoid merging it.
- If such PR gets merged, the build will fail on production which is not desirable.
- Knowing problems beforehand will help us fix them earlier.

What to do?
- run `npm ci` (why not `npm install`? refer this one: https://docs.github.com/en/free-pro-team@latest/actions/guides/building-and-testing-nodejs)
- run `npm run build` 
- TODO: run for tests once we have them in place

Refer: https://github.com/Real-Dev-Squad/website-crypto/blob/develop/.github/workflows/node.js.yml

**Comment by agarwalamn** [comment]
Please checkout https://github.com/Real-Dev-Squad/website-status/pull/34
