### ISSUE TITLE
Display image of the user working on a task alongside their name

### ISSUE THREAD

**Issue by Maheima** [Real-Dev-Squad/website-status#331]
Currently, the images shown alongside are only of the members and not of the registered users who have been assigned tasks. The goal is to display the images of all users who have their images uploaded on the site and show a dummy image otherwise.

**Comment by HeyNitin** [comment]
Hey Maheima, can you please assign it to me?

**Comment by Maheima** [comment]
Done! All the best!

**Comment by Maheima** [comment]
This issue will get resolved with this PR https://github.com/Real-Dev-Squad/website-status/pull/310/files
