### ISSUE TITLE
Add sorting options for idle users

### ISSUE THREAD

**Issue by RitikJaiswal75** [Real-Dev-Squad/website-status#336]
## Issue
The users on the [idle users' page](https://status.realdevsquad.com/idle-members) are sorted ed based on the alphabet. Change it to sort by date.

### Description
Currently, the users on the idle users' page of the status site are sorted based on their names this creates a problem as there might be some people who might not show up on top and might be without a task for a long time. This makes the growth of people slow.

### How will this help?
This will help in creating tasks and assigning them to people in an efficient manner such that there are fewer people without a task and everyone learns and grows.

### Steps to take:
1. Get necessary firestore indices created for usersStatus collection https://github.com/Real-Dev-Squad/website-backend/issues/868
2. Sort users in the backend https://github.com/Real-Dev-Squad/website-backend/issues/855 | https://github.com/Real-Dev-Squad/website-backend/pull/856
3. Send `first_name`, `last_name` and `picture` for a user in usersStatus collection https://github.com/Real-Dev-Squad/website-backend/issues/875 | https://github.com/Real-Dev-Squad/website-backend/pull/877
4. Show sorted idle_users on the frontend https://github.com/Real-Dev-Squad/website-status/issues/344
5. Show member and user details on click https://github.com/Real-Dev-Squad/website-status/issues/376

### Solution
- create a feature to sort the users in the order of the date they told that they were without a task

**Comment by RitikJaiswal75** [comment]
Check out the big picture over here: https://github.com/Real-Dev-Squad/todo-action-items/issues/107

**Comment by Maheima** [comment]
Currently, we are not recording the time stamp of when the user marked themselves Idle. It will be solved here https://github.com/Real-Dev-Squad/website-my/issues/291 
Once this gets done, I'll resume working on this issue.
