### ISSUE TITLE
Integrated new Signup Flow 

### ISSUE THREAD

**Issue by ivinayakg** [Real-Dev-Squad/website-status#338]
## Issue
When signing in with GitHub send the page href in query params as `&state=`
- RFC - https://github.com/Real-Dev-Squad/website-backend/issues/688

### Description
When you visit the `main site` and click on login, you are redirected to the original GitHub login page. We want to emulate a similar scenario for the `status site`.

### Expected Flow
- User visits `welcome-site` for the first time
- User clicks on `sign-in-with-github`
- Now, they are redirected to the GitHub login page
- once the login is successful the user is expected to land back to the `status site`
- Example PR - https://github.com/Real-Dev-Squad/website-www/pull/277

**Comment by Maheima** [comment]
It is already fixed here https://github.com/Real-Dev-Squad/website-status/issues/349 so, we can close this issue
