### ISSUE TITLE
User tasks not being shown on "/mine" route

### ISSUE THREAD

**Issue by yesyash** [Real-Dev-Squad/website-status#375]
### Description
When a user who has already been assigned tasks visits the `/mine` route there are no tasks being displayed even if we get the required data from the `/self` API. 

#### Image For reference: 
![image](https://user-images.githubusercontent.com/56453897/208294623-3f2ef7df-6d7b-4280-9a10-a147e868a8a5.png)

**Comment by HeyNitin** [comment]
Hi @Maheima , can you please assign it to me

**Comment by kshitij430** [comment]
Hi, Please assign this task to me.

**Comment by kshitij430** [comment]
PR [#386](https://github.com/Real-Dev-Squad/website-status/pull/386), fixes the issue. Please review.

**Comment by sonai99** [comment]
Hey @Maheima 
You can assign this to me.

**Comment by yesyash** [comment]
@Maheima is this issue resolved by pr #386?
Can we close this?

**Comment by sonai99** [comment]
@yesyash I see this is the latest fix https://github.com/Real-Dev-Squad/website-status/pull/414 for this issue
This is also not merged and has 2 Unresolved conversations. Do let me know if you still want me to work on this issue
@Maheima

**Comment by Maheima** [comment]
Hey @sonai99 ,
That is the PR I gave you in reference to assigning you this ticket. Can you please continue the work on that which will involve you verifying what has been done, checking if it works fine, replying to any unresolved conversations and getting it reviewed and merged
