### ISSUE TITLE
Fix CSS of cards in idle-user tab

### ISSUE THREAD

**Issue by Maheima** [Real-Dev-Squad/website-status#395]
![Screenshot_20230110-222154](https://user-images.githubusercontent.com/42349041/211613309-e4db4dd0-24ff-4059-a18a-bc2951ecb643.png)

**Comment by shmbajaj** [comment]
Hey @Maheima assign this to me.

**Comment by samyakshah3008** [comment]
I would love to work on this task @Maheima, can you please assign me this task?
