### ISSUE TITLE
RTK query setup refactor

### ISSUE THREAD

**Issue by Muralidhar22** [Real-Dev-Squad/website-status#442]
## why this change
- Need to change file structure and refactor apiSlices for proper code structure ,enhances DX when contributing
## current
- `store.ts` : our redux store is mentioned in the root folder
- `apiSlices`: folder which contains the rtk query api's for data fetching
## change
- `app`: folder inside our `src` contains `store.ts`
- `services`: folder inside our `app` which contain our rtk api endpoints and base `api` end point

**Comment by shmbajaj** [comment]
@Muralidhar22 can you add more description to this issue?
cc: @Maheima
