### ISSUE TITLE
Unnecessary toast coming without any action by user

### ISSUE THREAD

**Issue by satyam73** [Real-Dev-Squad/website-status#458]
When going to the status-site and in not logged in state then this pop up shows up here even without any action done by user.
We have to fix this issue.
![image](https://user-images.githubusercontent.com/85296770/226136028-563f2fbc-d3e4-4763-9a0d-5e6bb1b8e46c.png)

**Comment by arpit01923** [comment]
I am able resolve this issue

**Comment by arpit01923** [comment]
Hey @satyam73 @Maheima I have gone through the issue
Issue is, for "/users/self" API user must be authenticated. The toast is shown when user is not signin. There are 2 ways to remove this issue -
1. If user is not authenticated, user not able to access status route
2. Simply remove the toastify from that api. 

Please suggest which way to choose

**Comment by ankushdharkar** [comment]
@arpit01923 @Maheima 
We want guest users (not-signed in) to be able to access the status page in a read-only mode.

I am okay with the toast being removed, but before moving forward with [2.], could you please look into why it was added into the API handler in the first place?

**Comment by arpit01923** [comment]
@ankushdharkar **could you please look into why it was added into the API handler in the first place?**

Didn't get this point?

**Comment by ankushdharkar** [comment]
@arpit01923 I think that API serves another purpose in the navbar, so would still require the token. Please check with the other developers.

**Comment by arpit01923** [comment]
@ankushdharkar 
Will check it.

**Comment by arpit01923** [comment]
Hey @satyam73 Already completed the issue, just merge is pending
