### ISSUE TITLE
Cancel pending requeset if user navigates away from page

### ISSUE THREAD

**Issue by whyDontI** [Real-Dev-Squad/website-status#51]
## Problem
When the user navigates away from the component when a request is in the pending state, we no longer care about the result and want to cancel a request that’s already sent

<a href="https://www.loom.com/share/4355d84b5ade44e4b18ef161aa6f3a64" target="_blank">Click to watch video of the problem</a>

### Docs
<a href="https://www.npmjs.com/package/axios#cancellation" target="_blank">Axios Cancellation docs</a>

**Comment by Ishikabaid** [comment]
I'd like to take this task.
