### ISSUE TITLE
Extract or Move Constants to Constants Folder from Components Folder

### ISSUE THREAD

**Issue by sahsisunny** [Real-Dev-Squad/website-status#527]
Move constants from components folder to a separate folder called "constants" to improve organization and maintainability of our codebase.

**Comment by sahsisunny** [comment]
some Constants file still in components folder - https://github.com/Real-Dev-Squad/website-status/blob/22e788a4afdcb4d3dea9b545a037450139b703be/src/components/tasks/constants.ts

**Comment by RitikJaiswal75** [comment]
![image](https://github.com/Real-Dev-Squad/website-status/assets/57758447/79bb8f95-e689-4873-93e2-7e3e57f0aa72)
As per the above screenshot closing as a false alarm
