### ISSUE TITLE
Header Icon and Title for Challenge Box

### ISSUE THREAD

**Issue by sumitd94** [Real-Dev-Squad/website-status#6]
This ticket requires 2 things

1. Adding the RealDevSquad Roadmap Icon on the header  (check the below image for ref)

![image](https://user-images.githubusercontent.com/29303618/95684247-f33e8100-0c0d-11eb-90c3-c5bdc62b8a55.png)

So this will be basically the Icon followed by `Roadmap` text.

2. Adding The title for the challenge Boxes. (Check the below image for ref)

![image](https://user-images.githubusercontent.com/29303618/95684291-4a445600-0c0e-11eb-8668-8d40e80c1fd4.png)

Fell free to reach out if in case any help needed !

**Comment by Harshi7016** [comment]
I see the commits and comment for which is linked to the pr of sumit, do let me know if there are changes required

**Comment by Harshi7016** [comment]
@whyDontI , @sumitd94  Could I know the font-family of the above, I tried different ways to figure it out but all in vain, I have proceeded with Roboto for now, if you guys let me know I will change the default font-family to the same

**Comment by Harshi7016** [comment]
style: logo changes and aligning #40
