### ISSUE TITLE
Testing Standup Feature

### ISSUE THREAD

**Issue by Pratiyushkumar** [Real-Dev-Squad/website-status#604]
issue - https://github.com/Real-Dev-Squad/website-status/issues/486

Testing to be done for the standup feature

ETA -  29/06/2023

**Comment by RitikJaiswal75** [comment]
Please mention an ETA

**Comment by Pratiyushkumar** [comment]
PR merged
https://github.com/Real-Dev-Squad/website-status/pull/656
