### ISSUE TITLE
Add Footer in the Task Details Page

### ISSUE THREAD

**Issue by kotesh-arya** [Real-Dev-Squad/website-status#614]
Currently, the task details page lacks the footer as shown below:
![image](https://github.com/Real-Dev-Squad/website-status/assets/69259490/2d2d2009-1be1-44ec-b2df-c274448d9065)

**Comment by bksh05** [comment]
I can take this task.

**Comment by kotesh-arya** [comment]
Assigned ✅

**Comment by bksh05** [comment]
Thanks @kotesh-arya, I will start working on this from today,

**Comment by bksh05** [comment]
I have created PR for this [here](https://github.com/Real-Dev-Squad/website-status/pull/631)
