### ISSUE TITLE
Replace the PIPE(|) Character with CSS divider

### ISSUE THREAD

**Issue by sahsisunny** [Real-Dev-Squad/website-status#659]
## Overview
Currently, we are using pipe characters to divide between the category tab it can be refactored by creating the CSS divider.

URL = https://status.realdevsquad.com
![image](https://github.com/Real-Dev-Squad/website-status/assets/70854507/606f883e-1a25-432e-957b-e927686c49ab)

**Comment by NagaSatyaGeeth** [comment]
Please assign this issue for me and can someone help me setup the website so that I can run it locally ? I have followed the given steps but I am getting some errors which I have tried to resolve but it was not getting resolved

**Comment by j24m** [comment]
> Please assign this issue for me and can someone help me setup the website so that I can run it locally ? I have followed the given steps but I am getting some errors which I have tried to resolve but it was not getting resolved

Hey, I have already started working on this task, please take another task.

**Comment by j24m** [comment]
Pr for this issue : 
-https://github.com/Real-Dev-Squad/website-status/pull/631
