### ISSUE TITLE
fix banner responsiveness for the task progress and standup feature

### ISSUE THREAD

**Issue by Pratiyushkumar** [Real-Dev-Squad/website-status#666]
Banner responsiveness for the task progress component and standup feature component should be fixed since currently the responsiveness is breaking.

![image](https://github.com/Real-Dev-Squad/website-status/assets/82165483/537ce5bb-fc3d-4e16-94e9-d3aef6237e8c)

![image](https://github.com/Real-Dev-Squad/website-status/assets/82165483/881f68da-13b4-4103-8cff-95735142cf58)

**Comment by j24m** [comment]
Hey, assign this to me. :)
