### ISSUE TITLE
migrate subscibeUser Api call to RTK Query 

### ISSUE THREAD

**Issue by bhtibrewal** [Real-Dev-Squad/website-status#673]
URL : {BASE_URL}/challenges/subscribe
### Requirement
- write RTK Query 
- write tests

**Comment by biswanathTewari** [comment]
i would like to take this task

**Comment by bhtibrewal** [comment]
Closing this issue and tracking the cleanup with https://github.com/Real-Dev-Squad/website-status/issues/696
