### ISSUE TITLE
Add a sign-in button on the Navbar

### ISSUE THREAD

**Issue by Maheima** [Real-Dev-Squad/website-status#738]
when user is remain signed out in #status-site-next-typescript, the profile icon is there in the navbar in place of the sign in button. 

There should be no dropdown menu that should appear when a user isn't signed in. Check member's side for reference.

https://www.loom.com/share/48bf36fdded64bfd9eba55d667d58942?sid=d8a3bd64-ba1c-437d-90de-a5ed28d24f36

**Comment by ankitbajpai65** [comment]
Can you add 14/08/23 as ETA of this issue.
Dev- 2-3 days, PR review - 3 days and 1 day buffer. Will try to finish earlier.

**Comment by ankitbajpai65** [comment]
Issue resolved here - https://github.com/Real-Dev-Squad/website-status/pull/813
