### ISSUE TITLE
[RFC] Design- for showing the Progress Update details

### ISSUE THREAD

**Issue by fakhruddinkw** [Real-Dev-Squad/website-status#855]
We are planning to take daily updates from the developer about the progress they have made so far on their task. Currently this is behind dev flag. 

It looks something like this:
![status](https://github.com/Real-Dev-Squad/website-status/assets/85249044/df738fac-d670-4a7b-b8fe-108ac08afffe)

Currently when we click on any of the updates, nothing is shown.

There are two ways we can achieve this:

1. We can either have a modal, like we have for extension request on my site:
    ![my-site-modal](https://github.com/Real-Dev-Squad/website-status/assets/85249044/7854aa17-78b9-4cc9-9c99-6402c66283b3)
    
2. Or we can have a collapsible list, like we have for members site:
   ![members-site-collapsible](https://github.com/Real-Dev-Squad/website-status/assets/85249044/d361db27-8261-4415-951a-14950d4827bd)
   
Here is the rough wireframe of proposed solution:
<img width="3375" alt="wireframe" src="https://github.com/Real-Dev-Squad/website-status/assets/85249044/0edd09bc-87a5-44d0-9bbf-621db1402ad1">

I would like Developers to comment on which would be a better option in this case, Thank you!

**Comment by Pratiyushkumar** [comment]
According to me, the first option would be better because as per the design of the task detail page accordion style would not fit. As an end user, I would like to see lists of updates, not the accordion-style lists where I will have to do 1 or 2 extra clicks. Generally, accordions are used for FAQ pages. and if we include the accordion then we will have to show task updates lists in the same which may be possible that a user scroll event occurs.

**Comment by bharati-21** [comment]
Prefer a modal as well. But we will also have to consider having a seamless experience on phones. We need to consider how we are rendering text (importantly quantity. We don't want to show jam packed text). 
Also are we going to always let the user select and filter based on the date and the kind of update (blocker, completed, and planned)? If yes, then preferably rendering the update and showing the filter should be done within the same modal screen. This would be an easier experience.

**Comment by fakhruddinkw** [comment]
> Also are we going to always let the user select and filter based on the date and the kind of update (blocker, completed, and planned)? If yes, then preferably rendering the update and showing the filter should be done within the same modal screen. This would be an easier experience.

Currently there is no filter as such.. we show all the updates the user has given in desc order of date. 
Also, we show completed, blocked and planned as a kind of a single form. We do not filter based on them.
