### ISSUE TITLE
Show readable date format in tasks

### ISSUE THREAD

**Issue by ankurnarkhede** [Real-Dev-Squad/website-status#86]
We should see a human readable date string on the site, let's implement according to this design:

https://www.figma.com/file/KAV9FsUXlzhdFbHBADiZSk/Task-Row?node-id=0%3A1

The UI for tasks is currently showing the unix timestamp

**Comment by whyDontI** [comment]
Let's divide this issue into 2 phases.
1) No need to make any UI changes, just the `Date` should be readable.
    > We need this feature on priority, we'll try to get it merged ASAP

2) Make is as mentioned in the issue description
