### ISSUE TITLE
Sort the Progress update on status site.

### ISSUE THREAD

**Issue by Amandixit10** [Real-Dev-Squad/website-status#875]
## Overview
Currently the functionality to update the task progress on status site is under feature flag. If a user updates the task progress, the task are not in a sorted order. This makes it difficult to track the task status. Sort the task so that tracking task status will become easier. 

![image](https://github.com/Real-Dev-Squad/website-status/assets/55151241/871b1a42-2aa2-4ffd-9056-eb42597f7108)

Here you can see task progress is not sorted.

**Comment by skv93-coder** [comment]
Please assign this issue to me.
