### ISSUE TITLE
Fix APIs being called before input is provided

### ISSUE THREAD

**Issue by prakashchoudhary07** [Real-Dev-Squad/website-status#891]
API calls for searching tasks and searching users are being made before input is provided

<img width="724" alt="image" src="https://github.com/Real-Dev-Squad/website-status/assets/34452139/6e0c1a97-79f1-4371-9ddf-ef72f99054b6">
<img width="763" alt="image" src="https://github.com/Real-Dev-Squad/website-status/assets/34452139/856fde72-178e-4b9c-878f-6e3f38d3b426">

You will be able to reproduce this in local, with super user access

**Comment by ajoykumardas12** [comment]
### Description:
On Issues page `https://dev.realdevsquad.com/issues?dev=true` api call for issues and assignee are being before any input is provided.
