### ISSUE TITLE
Change Search bar text from completed to done

### ISSUE THREAD

**Issue by Amandixit10** [Real-Dev-Squad/website-status#897]
### Overview
Currently on status site, when user want to navigate to done status, they can made it by selecting the DONE status option. Selecting one of the status options changes the search bar text to the status name for e.g if a user select overdue status, the text in search bar changes to status:overdue. But for DONE status option, the search text changes to status:completed. 

### Current behavior 
![image](https://github.com/Real-Dev-Squad/website-status/assets/55151241/6c37a2cf-c709-4b14-acd9-249296bf74be)

### Proposed behavior
![image](https://github.com/Real-Dev-Squad/website-status/assets/55151241/5c742b9e-19db-4cfe-83ad-030bc9b6435d)

**Comment by aneenajohn** [comment]
@Amandixit10 Please assign this task to me

**Comment by Amandixit10** [comment]
> @Amandixit10 Please assign this task to me

Sorry @aneenajohn but this issue has already been resolved and is under feature flag currently. Sorry for the inconvenience caused.

**Comment by Amandixit10** [comment]
This bug has already been resolved and is under feature flag.
