### ISSUE TITLE
Fix UI of issues tab

### ISSUE THREAD

**Issue by Maheima** [Real-Dev-Squad/website-status#898]
The content shouldn't go out of the issue card like shown in the image below

![image](https://github.com/Real-Dev-Squad/website-status/assets/42349041/961f0d21-8dc9-4d46-b68b-90bcd46dd999)

**Comment by shubhamjaintech** [comment]
Hi @Maheima , 
Can you please assign it to me? Thank you.

**Comment by shubhamjaintech** [comment]
@Maheima 
A. ![image](https://github.com/Real-Dev-Squad/website-status/assets/22474104/670c37d1-7267-4069-9887-76beefcb103c)
Prod server is giving 500 internal server error.
Link: https://status.realdevsquad.com/issues

*Same happening when i did local setup 
![image](https://github.com/Real-Dev-Squad/website-status/assets/22474104/1b26ac58-63ac-4c29-930e-4853b3675641)

Am i missing something or this is a bug of BE/API?
