### ISSUE TITLE
[Issue] - Disabled button is getting clicked in update progress

### ISSUE THREAD

**Issue by satyam73** [Real-Dev-Squad/website-status#916]
### Description 
When going to the update progress we get redirected to form to update our task progress. In initial state there's no data present in the from and the button is disabled in state(as it looks in UI). But when we try to click the button with empty form it gets clicked and the API is also being called which shouldn't happen.
### Step to Reproduce
- Go to any of your task and click on `Update Progress`.
![image](https://github.com/Real-Dev-Squad/website-status/assets/85296770/cf75c0c6-f82d-4ce2-8604-dd24dafaef96)
- You will see a form like this as in image,
![image](https://github.com/Real-Dev-Squad/website-status/assets/85296770/6fb78082-3f6e-48a6-bc88-b62300b13a4b)
- Try submitting the form with empty values.
- It will get clicked which shouldn't happen and the toast will appear(as in image below).
![image](https://github.com/Real-Dev-Squad/website-status/assets/85296770/ff8036ce-59cb-4de1-8781-91c2574783cf)

### Possible solution
- Try seeing if the disabled  attribute is being set in the button or not. 
- If not set the disabled attribute to true when there is no data and set it to false when the form gets filled with the help of state variable.

### Reference Video
https://github.com/Real-Dev-Squad/website-status/assets/85296770/40512aae-0b67-43be-b6ac-9cacac4806e8

**Comment by aneenajohn** [comment]
@satyam73/ @tejas, Can you please assign this task to me

**Comment by skt17** [comment]
ETA 10th of October 2023
