### ISSUE TITLE
TasksContent Component Refactor

### ISSUE THREAD

**Issue by ajoykumardas12** [Real-Dev-Squad/website-status#917]
### **Related Issue:**
- #896 

### **Description**
TasksComponent has become hard to maintain due to having too many states, causing unnecessary re-renders and also making an unnecessary api call for fetching tasks with previous query states. When implementing multiple assignee tasks search, these problems are causing unwanted side effects (eg, fetching tasks for old assignees value when searching for multiple assignes until unless refreshed). So the component has to be refactored before completing issue #896 .
This refactor will also help future feature implementations by simplifying the component.

### **Screenshots**
![Screenshot](https://github.com/Real-Dev-Squad/website-status/assets/87164140/9a6f53ce-809f-4e96-bdd0-13eb99d6ab5d)

The above screenshot shows two same api calls made when searching tasks for assignee 'ajoy-kumar' after pressing search button.

**Comment by sahsisunny** [comment]
> Design Doc: [Google Docs Link](https://docs.google.com/document/d/19f2RyZio1nGJf-YhHzWx2dVuYUpTC_nFzhQizxGqEBk/edit?usp=sharing)

LGTM :+1:

**Comment by ajoykumardas12** [comment]
Closed by pull #915
