### ISSUE TITLE
Width on desktop 750px for Accordion Title

### ISSUE THREAD

**Issue by ankushdharkar** [Real-Dev-Squad/website-status#93]
![image](https://user-images.githubusercontent.com/1935403/112183688-b9f63e00-8bbb-11eb-8baa-1cf6b9ceb855.png)

**Comment by sebuelias** [comment]
Can I take this issue?
Also, how do I get these active / Pending accordions?
When I run the dev build it shows nothing.
![image](https://user-images.githubusercontent.com/10326494/113129916-15b66c00-9239-11eb-9266-bd5e97d54cb0.png)

**Comment by sebuelias** [comment]
On changing the maximum width to 750px it will look like this : 
![image](https://user-images.githubusercontent.com/10326494/114281270-1c27bd80-9a5b-11eb-9ea8-957da6208829.png)

Is this ok?
