### ISSUE TITLE
Show status of task on status page

### ISSUE THREAD

**Issue by skv93-coder** [Real-Dev-Squad/website-status#936]
# Show Task status
## Overview

In Read Dev Squad, we want to be able to know the status of task, but currently the user has to click on task and wait for task to load to know the status. This feature will save the time.

![image](https://github.com/Real-Dev-Squad/website-status/assets/68867418/6ec327be-7139-4474-9f95-bfd7073f643a)

## User stories

- As a user, I should be able to know the status of task on task card itself.

## Requirements

- UI is needed to show how the status should be rendered. (Until UI is not provided the feature will remain under feature flag.)

## Acceptance Criteria

- [ ] As as user, I should be able look at the status of task on opening task page.

**Comment by ajoykumardas12** [comment]
closed via #959
