### ISSUE TITLE
Fix: Add a hover effect on the button in Progress updates

### ISSUE THREAD

**Issue by vikhyat187** [Real-Dev-Squad/website-status#948]
<img width="911" alt="image" src="https://github.com/Real-Dev-Squad/website-status/assets/52795644/1552c1d0-f641-43d6-885a-54d9a8742c1a">
Here the submit button, should have hover effect and also have some slight css change

**Comment by devananth** [comment]
I would like to work on this issue. Can you assign me this please ?

**Comment by ajoykumardas12** [comment]
closed via #1046
