### ISSUE TITLE
Remove border from task card

### ISSUE THREAD

**Issue by ankushdharkar** [Real-Dev-Squad/website-status#95]
We would not be wanting this black border to appear anymore:

![image](https://user-images.githubusercontent.com/1935403/112640931-17c69800-8dff-11eb-987b-98aafbd2ecff.png)

**Comment by sebuelias** [comment]
I would like to take this issue.
But on removing the border it might look a little bad, so any suggestions on what to do after? Or leave It as is?

**Comment by swarajpure** [comment]
> I would like to take this issue.
> But on removing the border it might look a little bad, so any suggestions on what to do after? Or leave It as is?

One idea I can think of is, to have a look at the member cards on `members.realdevsquad.com`

**Comment by sebuelias** [comment]
Is this look fine? If not, please give inputs.
![image](https://user-images.githubusercontent.com/10326494/113450066-cc267680-941c-11eb-8be1-5d72d83b98a6.png)

Or do I have to make any other changes?

Also if I have some suggestion as to may be modify in the same component, I need to raise a new issue and get it approved, right?

**Comment by swarajpure** [comment]
> Is this look fine? If not, please give inputs.
> ![image](https://user-images.githubusercontent.com/10326494/113450066-cc267680-941c-11eb-8be1-5d72d83b98a6.png)
> 
> Or do I have to make any other changes?
> 
> Also if I have some suggestion as to may be modify in the same component, I need to raise a new issue and get it approved, right?

Looks good to me. You can make a PR. Make sure to add screenshots of before and after so the reviewers know what's done.
