### ISSUE TITLE
Create a success message and close icon for task creation requests

### ISSUE THREAD

**Issue by Ajeyakrishna-k** [Real-Dev-Squad/website-status#977]
## Description: 
Once a user submits a task request a success message will be shown with a link which can be shared with a super user to get the request approved.

PRD : https://docs.google.com/document/d/1El7k9XrwWIoR3I-7udS-cg0XxVb3InjOU4Cw3qK565g

#### For super users: 
 
| Header 1 | Header 2 |
|----------|----------|
| Width | 330px | 
| Height | 390px |
| padding | 15px | 

<img width="369" alt="Screenshot 2023-11-06 at 2 58 51 AM" src="https://github.com/Real-Dev-Squad/website-status/assets/98796547/36ffda2c-6bd6-4ff6-97b7-4e42fcf159fe">

#### For users: 

| Header 1 | Header 2 |
|----------|----------|
| Width | 300px | 
| Height | 330px |
| padding | 15px | 

<img width="393" alt="Screenshot 2023-11-06 at 2 58 39 AM" src="https://github.com/Real-Dev-Squad/website-status/assets/98796547/81dc1c96-b7ae-4c0e-9e16-89afab7c3e38">

- [x] Close Icons design:
<img width="415" alt="Screenshot 2023-11-04 at 4 42 34 AM" src="https://github.com/Real-Dev-Squad/website-status/assets/98796547/73ff9a14-337e-4b56-ad23-be397a48bb26">

**Comment by Ajeyakrishna-k** [comment]
Is there any better suggestions for the message?

**Comment by sahsisunny** [comment]
> Is there any better suggestions for the message?

My profile has the tag "group-project-managers" and I have no privilege to assign tasks to users.

**Comment by Ajeyakrishna-k** [comment]
> > Is there any better suggestions for the message?
> 
> My profile has the tag "group-project-managers" and I have no privilege to assign tasks to users.

- Not sure why we have to relate a discord role to the more general term `project manager`. 
- Do you have any better suggestions?
