### ISSUE TITLE
Feature Requirement document -- Task details page edit functionally for super user

### ISSUE THREAD

**Issue by skv93-coder** [Real-Dev-Squad/website-status#982]
# Task details -- Edit mode
## Overview

In Real Dev Squad, the super user want to do all the actions related to editing (which they can do in task card in edit mode) in task details page as many user usually send the links of task details page.

Reference video:-
[screen-capture (3).webm](https://github.com/Real-Dev-Squad/website-status/assets/68867418/7fc7ff8e-b584-473f-bfa5-9504d522a2d7)

## User stories

- As a super user, I should be able to change ETA, assignee,progress and status of any task.

## Requirements
No

## Acceptance Criteria

- [ ] As a super user, I should be able to change ETA, assignee,progress and status of any task by opening task details page by the link /task/:id.

**Comment by ajoykumardas12** [comment]
closed via #995
